# Generated by Django 5.1.2 on 2024-10-12 14:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GroundObject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        choices=[("standard", "Standard"), ("emergent", "Emergent")],
                        default="standard",
                        max_length=10,
                    ),
                ),
                ("lat", models.FloatField()),
                ("long", models.FloatField()),
                (
                    "shape",
                    models.CharField(
                        choices=[
                            ("circle", "Circle"),
                            ("semicircle", "Semi-Circle"),
                            ("quartercircle", "Quarter-Circle"),
                            ("triangle", "Triangle"),
                            ("rectangle", "Rectangle"),
                            ("pentagon", "Pentagon"),
                            ("star", "Star"),
                            ("cross", "Cross"),
                        ],
                        default="circle",
                        max_length=15,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("black", "Black"),
                            ("red", "Red"),
                            ("blue", "Blue"),
                            ("green", "Green"),
                            ("purple", "Purple"),
                            ("brown", "Brown"),
                            ("orange", "Orange"),
                        ],
                        default="black",
                        max_length=10,
                    ),
                ),
                ("text", models.CharField(max_length=100)),
                (
                    "text_color",
                    models.CharField(
                        choices=[
                            ("black", "Black"),
                            ("red", "Red"),
                            ("blue", "Blue"),
                            ("green", "Green"),
                            ("purple", "Purple"),
                            ("brown", "Brown"),
                            ("orange", "Orange"),
                        ],
                        default="black",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ground Object",
                "verbose_name_plural": "Ground Objects",
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="files/")),
                ("title", models.CharField(max_length=100)),
                (
                    "image_type",
                    models.CharField(
                        choices=[("visible", "Visible"), ("thermal", "Thermal")],
                        default="visible",
                        max_length=20,
                    ),
                ),
                ("taken_at", models.DateTimeField()),
                ("longitude", models.FloatField(null=True)),
                ("latitude", models.FloatField(null=True)),
                ("altitude", models.FloatField(null=True)),
            ],
        ),
    ]
