# Generated by Django 5.0.6 on 2024-06-05 02:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CameraImage',
            fields=[
                ('timestamp', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='imgs')),
            ],
        ),
        migrations.CreateModel(
            name='GroundObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('type', models.CharField(choices=[('S', 'Standard'), ('E', 'Emergent')], default='E', max_length=1)),
                ('shape', models.CharField(blank=True, choices=[('CIR', 'Circle'), ('SCR', 'Semi Circle'), ('QCR', 'Quarter Circle'), ('TRI', 'Triangle'), ('RCT', 'Rectangle'), ('PNT', 'Pentagon'), ('STR', 'Star'), ('CRS', 'Cross')], max_length=3)),
                ('color', models.CharField(blank=True, choices=[('BLK', 'Black'), ('RED', 'Red'), ('BLU', 'Blue'), ('GRE', 'Green'), ('PUR', 'Purple'), ('BWN', 'Brown'), ('ORG', 'Orange')], max_length=3)),
                ('text', models.CharField(blank=True, max_length=16)),
                ('text_color', models.CharField(blank=True, choices=[('BLK', 'Black'), ('RED', 'Red'), ('BLU', 'Blue'), ('GRE', 'Green'), ('PUR', 'Purple'), ('BWN', 'Brown'), ('ORG', 'Orange')], max_length=3)),
            ],
        ),
    ]
