# Generated by Django 5.0.6 on 2024-09-29 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                ("title", models.CharField(max_length=100)),
                (
                    "image_type",
                    models.CharField(
                        choices=[("visible", "Visible"), ("thermal", "Thermal")],
                        default="visible",
                        max_length=20,
                    ),
                ),
                ("taken_at", models.DateTimeField()),
                ("longitude", models.FloatField(null=True)),
                ("latitude", models.FloatField(null=True)),
                ("altitude", models.FloatField(null=True)),
            ],
        ),
    ]
