# Generated by Django 5.0.6 on 2024-10-11 01:54
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0002_alter_image_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroundObject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        choices=[("standard", "Standard"), ("emergent", "Emergent")],
                        default="standard",
                        max_length=10,
                    ),
                ),
                ("lat", models.FloatField()),
                ("long", models.FloatField()),
                (
                    "shape",
                    models.CharField(
                        choices=[
                            ("circle", "Circle"),
                            ("semicircle", "Semi-Circle"),
                            ("quartercircle", "Quarter-Circle"),
                            ("triangle", "Triangle"),
                            ("rectangle", "Rectangle"),
                            ("pentagon", "Pentagon"),
                            ("star", "Star"),
                            ("cross", "Cross"),
                        ],
                        default="circle",
                        max_length=15,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("black", "Black"),
                            ("red", "Red"),
                            ("blue", "Blue"),
                            ("green", "Green"),
                            ("purple", "Purple"),
                            ("brown", "Brown"),
                            ("orange", "Orange"),
                        ],
                        default="black",
                        max_length=10,
                    ),
                ),
                ("text", models.CharField(blank=True, max_length=100)),
                (
                    "text_color",
                    models.CharField(
                        choices=[
                            ("black", "Black"),
                            ("red", "Red"),
                            ("blue", "Blue"),
                            ("green", "Green"),
                            ("purple", "Purple"),
                            ("brown", "Brown"),
                            ("orange", "Orange"),
                        ],
                        default="black",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ground Object",
                "verbose_name_plural": "Ground Objects",
            },
        ),
    ]
