# Generated by Django 5.0.6 on 2024-10-11 03:29
import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0003_groundobject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groundobject",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("06c69cbe-e0e0-4826-9b9d-d5595736b125"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
