# Generated by Django 5.0.6 on 2024-10-11 03:52
import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0004_alter_groundobject_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groundobject",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("ad489f08-a80c-4e7d-b33d-3d48b614a117"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
