# Generated by Django 5.0.6 on 2024-10-11 03:54
import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0005_alter_groundobject_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groundobject",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("4c973e1d-3e90-4357-bad0-37c39c1bff2e"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
