# Generated by Django 5.0.6 on 2024-10-11 22:50
import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0009_alter_groundobject_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groundobject",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("2953b5cc-bb46-4420-87df-17d3e33c3f64"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
