# Generated by Django 5.1.5 on 2025-01-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drone", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoordinateOfInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("name", models.CharField(max_length=100, null=True)),
                ("description", models.TextField(null=True)),
            ],
        ),
    ]
