# Generated by Django 5.0.6 on 2024-06-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DroneTelemetry',
            fields=[
                ('timestamp', models.IntegerField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('vertical_speed', models.FloatField()),
                ('speed', models.FloatField()),
                ('heading', models.FloatField()),
                ('battery_voltage', models.FloatField()),
            ],
        ),
    ]
