name: Upload Docker Image to Docker Hub

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set lowercase repository name
      run: echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USER }}/gcom-2025:${{ github.sha }} .

    - name: Tag Docker image as latest
      run: docker tag ${{ secrets.DOCKER_USER }}/$REPO_NAME:${{ github.sha }} ${{ secrets.DOCKER_USER }}/$REPO_NAME:latest

    - name: Push Docker image to Docker Hub with commit SHA tag
      run: docker push ${{ secrets.DOCKER_USER }}/$REPO_NAME:${{ github.sha }}

    - name: Push Docker image to Docker Hub with latest tag
      run: docker push ${{ secrets.DOCKER_USER }}/$REPO_NAME:latest
