name: Upload Docker Image to Docker Hub

on:
  pull_request:
    branches:
      - main
      - release
  push:
    branches:
      - main
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and Push (Release Branch)
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/release/')
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64, linux/arm64
        push: true
        tags: ubcuas/${{ github.event.repository.name }}:latest

    - name: Build (Non-Release Branch)
      if: github.ref != 'refs/heads/release/*'
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        push: false
        tags: ubcuas/${{ github.event.repository.name }}:latest
