name: Linters

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: black
        uses: psf/black@stable
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: ruff  
        uses: chartboost/ruff-action@v1
